### ISSUE TITLE
Rename the repo to `cherry-picker`

### ISSUE THREAD

**Issue by webknjaz** [python/cherry-picker#10]
So that in fs the path to the package would be `cherry-picker/cherry_picker` and not `cherry_picker/cherry_picker` which is less confusing + it's a good practice to have a repo name not being python importable which prevents some other confusions when you're in the wrong dir.

**Comment by Mariatta** [comment]
Thanks. I've renamed this to cherry-picker, seeing how we have the-knights-who-say-ni, core-workflow, and miss-islington.
