### ISSUE TITLE
[TODO] Complete dropping support for Python 3.8

### ISSUE THREAD

**Issue by webknjaz** [python/cherry-picker#136]
https://github.com/python/cherry-picker/pull/133 did this for CI already, but there are two pieces of the metadata that still advertise 3.8: `Require-Python` and Trove classifiers.

* https://github.com/python/cherry-picker/blob/e2540af/pyproject.toml#L13
* https://github.com/python/cherry-picker/blob/e2540af/pyproject.toml#L18

**Comment by hugovk** [comment]
Thanks, would you like to open a PR?

**Comment by webknjaz** [comment]
I think it's a `good first issue` so I'll let someone else do that.

**Comment by webknjaz** [comment]
@hugovk perhaps add the `hacktoberfest` labels to the issue and the repo?

**Comment by hugovk** [comment]
Sure! Issue labelled. I don't have permission to add topics to the repo, but can add `hacktoberfest-accepted` to a PR.

**Comment by webknjaz** [comment]
@hugovk ack. @OlenaYefymenko will make the PR soon.
