### ISSUE TITLE
Add `cherry-picker` to `cpython` PyPI organisation

### ISSUE THREAD

**Issue by hugovk** [python/cherry-picker#142]
Following https://discuss.python.org/t/request-python-organisation-on-pypi/26545, let's move this package as the first into the https://pypi.org/org/cpython/ organisation.

**Comment by hugovk** [comment]
When I visit https://pypi.org/manage/organization/cpython/projects/ it says:

> There are no projects in your organization, yet. Get started by adding a project that you own using the form below.

https://docs.pypi.org/organization-accounts/actions/project-actions/#transfer-a-project says on transferring a project to an org:

> This action is applicable only if the owner has pre-existing projects associated with their individual user account.

I'm not an owner of cherry-picker so it's not in the form and cannot add it to the org.

At https://pypi.org/project/cherry-picker/ I see @brettcannon, @Mariatta and a "[core-workflow](https://pypi.org/user/core-workflow/)" account listed as maintainers. If one of you are owners of the PyPI project, please could you also add me as owner so I can transfer it to the org? Or we can make one or both of you also owners of the org and you can transfer it in?

**Comment by Mariatta** [comment]
Sure, can you add me as a maintainer on the org so I can move the project there?

**Comment by hugovk** [comment]
I added you as a manager to both cpython and python (I did both so we don't have to remember which one). If manager doesn't work, I'll change it to owner.

<img width="801" alt="image" src="https://github.com/user-attachments/assets/8a3bc12a-ec38-45a4-a77c-5ae442a30d82">

**Comment by Mariatta** [comment]
It's done.

**Comment by Mariatta** [comment]
https://pypi.org/project/cherry-picker/ is now under CPython org

**Comment by hugovk** [comment]
There it is, thank you!

https://pypi.org/org/cpython/

**Comment by Mariatta** [comment]
This might be a bug with PyPA / warehouse, but somehow I got removed from "cherry-picker"'s maintainer list 😢

**Comment by AA-Turner** [comment]
I believe it's intentional -- you can add yourself back as a maintainer (or at least the same thing happened when I moved to PyPI organisations for several projects).

A

**Comment by AA-Turner** [comment]
Now that we have organisation accounts, is the [`core-workflow`](https://pypi.org/user/core-workflow/) account still needed? I'm not sure who has access to it...

A

**Comment by Mariatta** [comment]
Well it seems like a bug that the other maintainers are kept on the project but as the original project owner I got removed from it.
I could not figure out how to add myself back to the project, the manage members are not showing up for the cherry-picker project on PyPI.

I think Brett has the access to the core-workflow email.

**Comment by hugovk** [comment]
@Mariatta I've added you back as owner to the project:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/83418a73-7026-4fbd-b889-bb41ccaf1b06">

<img width="821" alt="image" src="https://github.com/user-attachments/assets/a8ab1eeb-7095-4d68-8a1c-f691a6425c3e">

**Comment by Mariatta** [comment]
Thank you!

**Comment by brettcannon** [comment]
> I think Brett has the access to the core-workflow email.

I have the account, but it doesn't even have 2FA signed up, so I think it's okay to remove it from the project now that an org account is attached.

**Comment by hugovk** [comment]
Now removed!
