### ISSUE TITLE
automatic conflict resolution for argument clinic generated files?

### ISSUE THREAD

**Issue by asottile** [python/cherry-picker#18]
For example, this backport could have been automated (the only conflict was on the AC hashes):

- https://github.com/python/cpython/pull/21066
- https://github.com/python/cpython/pull/21097
- https://github.com/python/cpython/pull/21098

perhaps even a [custom merge driver](https://git-scm.com/docs/gitattributes#_defining_a_custom_merge_driver) could be written for this?

**Comment by Mariatta** [comment]
Yeah.. I think this is same issue brought up in https://github.com/python/miss-islington/issues/41

**Comment by asottile** [comment]
sweet, let's continue the discussion there!
