### ISSUE TITLE
cherry_picker hardcodes the name of the python/cpython.git repo

### ISSUE THREAD

**Issue by markshannon** [python/cherry-picker#19]
`cherry_picker` needs an option to specify the `git remote` name for the CPython repo.
Currently it is hardcoded to "upstream" or "origin", and can't be used if a meaningful name like "python" is used
E.g.
```
~/repos/cpython$ git remote -v
python	git@github.com:python/cpython.git (fetch)
python	git@github.com:python/cpython.git (push)
mine	git@github.com:markshannon/cpython.git (fetch)
mine	git@github.com:markshannon/cpython.git (push)
```

**Comment by Mariatta** [comment]
Perhaps we can add yet another option to specify the `upstream`.
Right now it only recognizes either `upstream` or `origin`.

https://github.com/python/cherry-picker/blob/39e8d6d10eecae6b6d096e3e03b69c5104ba5507/cherry_picker/cherry_picker.py#L137-L146

PR is welcome.
