### ISSUE TITLE
Move cherry-picker's readme to readthedocs or something

### ISSUE THREAD

**Issue by Mariatta** [python/cherry-picker#3]
The readme for cherry-picker is getting long. Perhaps we can have documentation hosted in readthedocs or something similar.

**Comment by jaraco** [comment]
I'd actually recommend not to publish the readme on RTD. It will add additional workflows and toil to the project, and for what? The readme is already hosted on Github and PyPI. I would suggest maybe separating the changelog out into a separate file. I don't feel super-strongly about it, but in my projects, I only use RTD when there's need for more context (generated content, API docs, etc) with high readership (many docs are fine to be hosted in Github).

**Comment by hugovk** [comment]
We could use GitHub Pages to publish the README.

It would RST converting to Markdown, but here's a quick demo just by renaming: https://hugovk.github.io/cherry-picker/

I turned it on at https://github.com/hugovk/cherry-picker/settings/pages by selecting `main` and `/ (root)`:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/1324225/159158845-1fcd6bca-dd28-45c9-83f0-cd3acfa83464.png">

**Comment by hugovk** [comment]
> I'd actually recommend not to publish the readme on RTD. It will add additional workflows and toil to the project, and for what? The readme is already hosted on Github and PyPI. I would suggest maybe separating the changelog out into a separate file. I don't feel super-strongly about it, but in my projects, I only use RTD when there's need for more context (generated content, API docs, etc) with high readership (many docs are fine to be hosted in Github).

I agree with this.

Please see PR #104 to move the changelog to its own file.
