### ISSUE TITLE
Cut a new release.

### ISSUE THREAD

**Issue by jaraco** [python/cherry-picker#48]
#26 (and maybe others) have been fixed for some time, but continue to cause toil because the fix isn't visible to users. Can we get a release cut?

I see from the readme there's some release automation. As a core committer, can I cut a release?

**Comment by Mariatta** [comment]
Sorry for missing this ticket.
Yes, you can go ahead and cut a release. Ensure the version number and readme are up to date.
Release can be triggered by tagging it on GitHub, per instructions: https://github.com/python/cherry-picker#publishing-to-pypi

**Comment by jaraco** [comment]
I created https://github.com/python/cherry-picker/tree/release and tagged it per the instruction. Then I went to check the CI, but it looks like it doesn't exist. 
![image](https://user-images.githubusercontent.com/308610/133711250-369b0e04-b27b-4198-8cf3-29bdb004207d.png)
Is CI meant to be configured?

**Comment by jaraco** [comment]
I think part of the problem is the badge in the repo points to `www.travis-ci.com`. If I change that to `app.travis-ci.com`, I can then see the CI runs, but it doesn't include anything from my pushed release branch.

**Comment by jaraco** [comment]
Marietta cut the release in https://github.com/python/cherry-picker/issues/53#issuecomment-965524906.
