### ISSUE TITLE
Further automation for releasing cherry-picker.py

### ISSUE THREAD

**Issue by Mariatta** [python/cherry-picker#5]
Thanks to #262 (@webknjaz) I can publish to PyPI from Travis CI, all within GitHub web interface, and without going to the command line.

But I found myself still doing several manual steps:
- created the release branch
- drop the ".devX" from the version info (in `__init__.py`)
- create the tag
- merge the release branch
- bump the version number and add ".devX" to the version info.

Can this be made even simpler? Perhaps I was doing unnecessary steps?

I think that creating the release branch, dropping ".devX", and creating tag can be fully automated somehow.

**Comment by hugovk** [comment]
Releasing is now automated via Trusted Publishing:

* https://github.com/python/cherry-picker/pull/94
* https://github.com/python/cherry-picker/blob/main/RELEASING.md
