### ISSUE TITLE
Release process needs testing

### ISSUE THREAD

**Issue by jaraco** [python/cherry-picker#53]
In #48, I attempted to cut a new release, but when I followed the instructions, nothing happened. As I was working to figure it out, I found other problems (like the travis-ci badge is a 404 and the release branch didn't run in CI).

**Comment by Mariatta** [comment]
I will try to release it manually by hand today.

**Comment by Mariatta** [comment]
I've published v 2.1.0 to PyPI: https://pypi.org/project/cherry_picker/2.1.0/

**Comment by jaraco** [comment]
Oh, nice. Thanks for that!

In #54, I converted the release process to rely on Github Actions. It's based on the same process I use with my other projects, but the diff is untested.

It does require your help, though. Can you add a secret to the project? `PYPI_TOKEN` and with a value containing the token for PyPI? Then next time we have a release, we can see if the new process works.

**Comment by Mariatta** [comment]
Sure, do I add it as "Environment secret" or "repository secret"? Wasn't sure what's the difference there.

**Comment by jaraco** [comment]
Oh, I was unaware of the distinction. I use repository secrets, so I'd recommend that.

**Comment by Mariatta** [comment]
Ok. The `PYPI_TOKEN` has been added. Thanks.

**Comment by hugovk** [comment]
We're now using Trusted Publishers, hopefully things will be more better now: https://github.com/python/cherry-picker/pull/94.
