### ISSUE TITLE
Consider switching from `toml` to `tomli`

### ISSUE THREAD

**Issue by sobolevn** [python/cherry-picker#59]
`toml` was last released on 02.11.2020: https://pypi.org/project/toml/#history
There are multiple known bugs: https://github.com/uiri/toml/issues

Maintainer is not supporting their project: https://github.com/uiri/toml/issues/361

Multiple big projects like [`mypy`](https://github.com/python/mypy/blob/1ccefbdff922b502637009a77632a2be10256297/setup.py#L201), [`black`](https://github.com/psf/black/blob/31fe97e7ce1055debaa54bed9c63e252508a9a75/setup.py#L102), [`typeshed`](https://github.com/python/typeshed/blob/494481a0aed2ef0e00bbe190476ace0b8261bce6/requirements-tests.txt#L10) have already switched. 

The transition seems to be rather simple: basically swap `import toml` with `import tomli` and use a proper `encoding` when calling `loads`.

Related: https://www.python.org/dev/peps/pep-0680/

If this is something you think should be done, I can send a PR.

**Comment by hugovk** [comment]
[PEP 680](https://peps.python.org/pep-0680/) has been accepted and will be in Python 3.11 :tada:

I think it would be a good idea to switch from from `toml` to `tomli`, it will make it easier to switch to the stdlib `tomllib` at some point in the future.

**Comment by DanielNoord** [comment]
Sorry @sobolevn, I didn't notice the last sentence of your post. Not sure if you were already working on this, but I have created a PR which fixes this in #67.
